### ISSUE TITLE
add EventStorage just for consistency.

### ISSUE THREAD

**Issue by duyhungtnn** [bucketeer-io/android-client-sdk#111]
I mean we should rename EventDao to EventSQLDao.
Also, we might want to add EventStorage just for consistency.

_Originally posted by @yshrsmz in https://github.com/bucketeer-io/android-client-sdk/pull/89#discussion_r1342267017_

**Comment by cre8ivejp** [comment]
Done.
https://github.com/bucketeer-io/android-client-sdk/pull/89

**Comment by duyhungtnn** [comment]
Hi @cre8ivejp we were refactoring the EvaluationStorage in #89 
But its for the EventStorage.

**Comment by duyhungtnn** [comment]
I read the logic of the current EventInteractor & EventSQL.
The logic is simple and only SQLite. 
So I think we could skip this ticket for now.
