### ISSUE TITLE
Change the Rest API endpoint

### ISSUE THREAD

**Issue by cre8ivejp** [bucketeer-io/android-client-sdk#55]
#### Things to do

- Change all the fields in the request and the model data objects from snake_case to camelCase.
- Change the `reason` type from int to string ([reference](https://github.com/ca-dp/bucketeer-ios-sdk/pull/91/files#diff-4b6b4709ff9ff17fdcea065e22b91de7f8af39126450131e2966b7f487a7048a))
- Add protobuf @type ([reference](https://github.com/ca-dp/bucketeer-ios-sdk/pull/91/commits/dba1cf683b4385fb4dcc4a8fd61ce86fea2dba9a))
- Change the APIs

#### JSON object structure

In the new endpoint's response, there is no `data` object.

Before:

```
{
  data: {
    ...
  },
}
```

After:

```
{
  ...
}
```

#### New APIs

- get_evaluations
- register_events

E.g.
https:/api.example.com/get_evaluations
https:/api.example.com/register_events

PR Reference:
https://github.com/ca-dp/bucketeer-ios-sdk/pull/91

**Comment by cre8ivejp** [comment]
Please also, change the metadata key format from snake_case to CamelCase.

E.g.

```
appVersion
osVersion
deviceModel
deviceType
```

**Comment by duyhungtnn** [comment]
hi @cre8ivejp , I read the iOS's PR.
I found one field that didn't change to CamelCase.

Is it by design or is it missing out? 

<img width="930" alt="Screenshot 2023-05-23 at 16 23 38" src="https://github.com/bucketeer-io/android-client-sdk/assets/2597710/146cfa84-440e-4255-b083-869dc6ccbfa2">

source : [struct GetEvaluationSize](https://github.com/jinSasaki/bucketeer-ios-sdk/blob/ee4a38f0011c43c999c5964adf099404ed52b943/Bucketeer/Sources/Internal/Model/MetricsEventData.swift)

**Comment by cre8ivejp** [comment]
@duyhungtnn, thank you for reporting this.
I will fix it by today. The code has been moved to this [repository](https://github.com/bucketeer-io/ios-client-sdk), so if you need to check something in the code, use that repository.

**Comment by duyhungtnn** [comment]
hi @cre8ivejp , Should I increase the minSDK to 24? 

current when I run `./gradlew :bucketeer:lintDebug`  that will fail.

```
./src/main/kotlin/io/bucketeer/sdk/android/internal/event/db/EventDaoImpl.kt:30:

 Error: Call requires API level 24 (current min is 21): java.lang.Iterable#forEach [NewApi]
      events.forEach { event ->
```

**Comment by yshrsmz** [comment]
Hi @duyhungtnn

That error showed up because of the compatibility issue between Kotlin version & AGP version. That `forEach` should be a Kotlin extension function and not a Java method 🤔 

https://issuetracker.google.com/issues/185418482

**Comment by duyhungtnn** [comment]
> Hi @duyhungtnn
> 
> That error showed up because of the compatibility issue between Kotlin version & AGP version. That `forEach` should be a Kotlin extension function and not a Java method 🤔
> 
> https://issuetracker.google.com/issues/185418482

@yshrsmz  thank you for pointing that.

**Comment by duyhungtnn** [comment]
I see one problem, in the `GetEvaluationLatencyMetricsEvent` 
```kotlin
  data class GetEvaluationLatencyMetricsEvent(
    val labels: Map<String, String> = emptyMap(),
    // in seconds
    val duration: Long,
    @Json(name = "@type")
    val protobufType: String? = "type.googleapis.com/bucketeer.event.client.GetEvaluationLatencyMetricsEvent",
  ) : MetricsEventData()
```

**Comment by duyhungtnn** [comment]
I see one problem, in the `GetEvaluationLatencyMetricsEvent` 
```kotlin
  data class GetEvaluationLatencyMetricsEvent(
    val labels: Map<String, String> = emptyMap(),
    // in seconds
    val duration: Long,
    @Json(name = "@type")
    val protobufType: String? = "type.googleapis.com/bucketeer.event.client.GetEvaluationLatencyMetricsEvent",
  ) : MetricsEventData()
```

The field `duration: Long` but in the server API has changed to `duration: google. protobuf.Duration`.
Currently, it caused the E2E test to fail.

_For example, before the expected value is **Long (2)** 
Now it required to **String("2s")**_

@cre8ivejp 

I am fixing it.

<img width="1068" alt="Screenshot 2023-05-26 at 16 08 40" src="https://github.com/bucketeer-io/android-client-sdk/assets/2597710/a6c41cf4-faaa-4fce-a716-c3a5e54c1453">

**Comment by duyhungtnn** [comment]
One more problem found 
We have 2 test fail, even on the main branch 

<img width="1351" alt="Screenshot 2023-05-26 at 18 56 54" src="https://github.com/bucketeer-io/android-client-sdk/assets/2597710/409801e0-d184-4ad2-a103-ba22d57df401">

**Comment by cre8ivejp** [comment]
@duyhungtnn, I ran the e2e test using the main branch on my machine, and it passed without errors.
Also, I ran our CI, and it passed.

![Screenshot 2023-05-26 at 21 43 16](https://github.com/bucketeer-io/android-client-sdk/assets/2486691/f38a167f-b3f2-419a-8810-841d24d0d022)

CI
https://github.com/bucketeer-io/android-client-sdk/actions/runs/5090553638/jobs/9150248823

Maybe it's a temporary error on your side?

**Comment by duyhungtnn** [comment]
@cre8ivejp It seems a local problem. I tried to run a CI pipeline with new PR on my repo and it passed 
https://github.com/duyhungtnn/android-client-sdk/actions/runs/5091983885/jobs/9152722671

**Comment by cre8ivejp** [comment]
Done https://github.com/bucketeer-io/android-client-sdk/pull/63.
