### ISSUE TITLE
Add new metrics events

### ISSUE THREAD

**Issue by cre8ivejp** [bucketeer-io/android-client-sdk#56]
#### Summary

We want to add and remove deprecated metric events from the SDK to improve our monitoring system.
Basically, we will make changes in the current implementation to support the new metrics. Nothing in particular.

We use Okhttp and Moshi for the API requests.

#### APIs

For `get_evaluations`, we will report all metrics events, Including the latency and size metrics events.
For `register_events`, we will only report error metrics, such as timeout, network, server errors, etc.

#### InternalErrorMetricsEvent

We will remove the `InternalErrorMetricsEvent`, and use `InternalServerErrorMetricsEvent` for 500 internal server errors and `InternalSdkErrorMetricsEvent` for SDK internal errors.

#### Labels

All the metrics events have a key/value map called `labels`.
In the labels, we will set the same `tag` that is used to initialize the SDK.

E.g

```json
{
  "tag": "android"
}
```

#### Metric event list

Metric list
https://github.com/bucketeer-io/bucketeer/blob/main/proto/event/client/event.proto#L119-L184

```proto
enum ApiId {
  UNKNOWN_API = 0;
  GET_EVALUATION = 1;
  GET_EVALUATIONS = 2;
  REGISTER_EVENTS = 3;
}

message LatencyMetricsEvent {
  ApiId api_id = 1;
  map<string, string> labels = 2;
  google.protobuf.Duration duration = 3;
}

message SizeMetricsEvent {
  ApiId api_id = 1;
  map<string, string> labels = 2;
  int32 size_byte = 3;
}

// HTTP Mapping: 400 Bad Request
message BadRequestErrorMetricsEvent {
  ApiId api_id = 1;
  map<string, string> labels = 2;
}

// HTTP Mapping: 401 Unauthorized
message UnauthorizedErrorMetricsEvent {
  ApiId api_id = 1;
  map<string, string> labels = 2;
}

// HTTP Mapping: 403 Forbidden
message ForbiddenErrorMetricsEvent {
  ApiId api_id = 1;
  map<string, string> labels = 2;
}

// HTTP Mapping: 404 Not Found
message NotFoundErrorMetricsEvent {
  ApiId api_id = 1;
  map<string, string> labels = 2;
}

// HTTP Mapping: 499 Client Closed Request
message ClientClosedRequestErrorMetricsEvent {
  ApiId api_id = 1;
  map<string, string> labels = 2;
}

// HTTP Mapping: 500 Internal Server Error
message InternalServerErrorMetricsEvent {
  ApiId api_id = 1;
  map<string, string> labels = 2;
}

// HTTP Mapping: 503 Service Unavailable
message ServiceUnavailableErrorMetricsEvent {
  ApiId api_id = 1;
  map<string, string> labels = 2;
}

message TimeoutErrorMetricsEvent {
  ApiId api_id = 1;
  map<string, string> labels = 2;
}

message NetworkErrorMetricsEvent {
  ApiId api_id = 1;
  map<string, string> labels = 2;
}

message InternalSdkErrorMetricsEvent {
  ApiId api_id = 1;
  map<string, string> labels = 2;
}

message UnknownErrorMetricsEvent {
  ApiId api_id = 1;
  map<string, string> labels = 2;
}
```

**Comment by duyhungtnn** [comment]
started

**Comment by duyhungtnn** [comment]
@cre8ivejp Should I need  support mapping & parse  2 deprecated events 
`GetEvaluationLatencyMetricsEvent` & `GetEvaluationSizeMetricsEvent` ?

**Comment by yshrsmz** [comment]
> Should I need support mapping & parse 2 deprecated events GetEvaluationLatencyMetricsEvent & GetEvaluationSizeMetricsEvent?

I implemented https://github.com/bucketeer-io/javascript-client-sdk too, and in that SDK I [removed those 2 events](https://github.com/bucketeer-io/javascript-client-sdk/blob/main/src/internal/model/MetricsEventData.ts). So it should be fine without these events.

**Comment by cre8ivejp** [comment]
Done.
